# Generated by Django 6.0.5 on 2026-06-20 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_storeuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_earned', models.PositiveIntegerField(default=0)),
                ('deductible_points', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(default='L1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to='users.storeuser')),
            ],
            options={
                'db_table': 'buyer_profile',
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('order_complete', 'order_complete'), ('admin_adjust', 'admin_adjust'), ('deduct', 'deduct')], max_length=30)),
                ('source_id', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='users.storeuser')),
            ],
            options={
                'db_table': 'point_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
