# Generated by Django 6.0.5 on 2026-06-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0002_alter_storeuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('full_reduction', '满减券')], default='full_reduction', max_length=30)),
                ('threshold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('total_quantity', models.IntegerField(default=0)),
                ('claimed_quantity', models.IntegerField(default=0)),
                ('per_user_limit', models.IntegerField(default=1)),
                ('include_delivery_fee', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupon_template',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', '可使用'), ('used', '已使用'), ('expired', '已过期')], default='available', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='orders.order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_coupons', to='coupons.coupontemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='users.storeuser')),
            ],
            options={
                'db_table': 'user_coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponRedeemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redeem_records', to='users.storeuser')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redeem_records', to='merchants.merchant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redeem_records', to='orders.order')),
                ('user_coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redeem_records', to='coupons.usercoupon')),
            ],
            options={
                'db_table': 'coupon_redeem_record',
            },
        ),
    ]
