# Generated by Django 6.0.5 on 2026-06-21 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0003_alter_merchant_min_order_amount'),
        ('orders', '0003_order_fulfillment_type_pickup_ready'),
        ('users', '0002_alter_storeuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delivery', '配送问题'), ('product', '商品问题'), ('other', '其他问题')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='users.storeuser')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='merchants.merchant')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='orders.order')),
            ],
            options={
                'db_table': 'ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_messages', to='users.storeuser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_message',
                'ordering': ['created_at'],
            },
        ),
    ]
