# Generated by Django 6.0.5 on 2026-06-20 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_fulfillment_type_pickup_ready'),
        ('products', '0001_initial'),
        ('users', '0002_alter_storeuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_quantity', models.IntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('order_deduct', '下单扣减'), ('merchant_adjust', '商家改库存'), ('batch_online', '批量上架'), ('batch_offline', '批量下架'), ('order_cancel', '订单取消回补')], max_length=30)),
                ('operated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledgers', to='users.storeuser')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledgers', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledgers', to='products.product')),
            ],
            options={
                'db_table': 'stock_ledger',
                'ordering': ['-operated_at'],
                'indexes': [models.Index(fields=['product_id', '-operated_at'], name='stock_ledge_product_8aabef_idx'), models.Index(fields=['reason'], name='stock_ledge_reason_02f4c4_idx')],
            },
        ),
    ]
