# Generated by Django 6.0.5 on 2026-06-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0002_alter_storeuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('quality', '商品质量问题'), ('wrong', '发错商品'), ('damaged', '商品破损'), ('not_received', '未收到货'), ('other', '其他原因')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('reject_reason', models.CharField(blank=True, choices=[('evidence_insufficient', '证据不足'), ('wrong_procedure', '流程不符'), ('timeout', '超出申请时限'), ('other', '其他原因')], default='', max_length=30)),
                ('reject_remark', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersales', to='users.storeuser')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersales', to='merchants.merchant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aftersales', to='orders.order')),
            ],
            options={
                'db_table': 'aftersale_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
