# Generated by Django 6.0.5 on 2026-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
