# Generated by Django 6.0.5 on 2026-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_supports_pickup_merchant_pickup_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
